### ISSUE TITLE
access with oracle user not available

### ISSUE THREAD

**Issue by silviocrivellini** [PhilippSalvisberg/docker-oracle12ee#3]
I'm login at the docker image as root. I would like to access as 'oracle' user since the 'oracle; user is defined and configured on this image.

sh-4.2# cd /home
sh-4.2# ls
oracle
sh-4.2# cat oracle/.bash_profile
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
export JAVA_HOME=/u01/app/oracle/product/12.2.0.1/dbhome/jdk
export ORACLE_HOME=/u01/app/oracle/product/12.2.0.1/dbhome
export ORACLE_BASE=/u01/app/oracle
export PATH=/usr/sbin:$PATH:/opt/sqlcl/bin
export PATH=$ORACLE_HOME/bin:$PATH
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
export CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
export TMP=/tmp
export TMPDIR=$TMP
export TERM=linux

but I receive following error:

sh-4.2# su - oracle
Last login: Tue May  2 12:25:43 UTC 2017
su: cannot open session: Permission denied

Any idea to login as oracle user ?

Best Regards, Silvio

**Comment by PhilippSalvisberg** [comment]
> Any idea to login as oracle user ?

use ```gosu oracle bash``` instead of ```su - oracle```. See also http://grokbase.com/t/gg/docker-user/162h4pekwa/docker-su-oracle-su-cannot-open-session-permission-denied

I haven't found out how to make the su command work with OL 7.3. However, I know it is possible since I've seen OL 7.3 installation with a working su command. I just need some time to find out... In the meantime I use the gosu command as a workaround in this and its dependent images.

HTH

**Comment by silviocrivellini** [comment]
Hi Philipp,
the gosu command is not enough, since I can access as 'oracle' user (cool!) but without the environment associated at this user.
So the initial issue is not yet resolved.
Silvio

**Comment by PhilippSalvisberg** [comment]
use ```.bashrc```instead of ```.bash_profile``` to define your environment variables.

**Comment by Dani3lSun** [comment]
Thus I had a similar issue I found some solution to have "higher" rights inside of a container, which means you can use su when the container runs in privileged mode (--privileged flag) or with more Linux capabilities (--cap-add SYS_RESOURCE flag)...
More details here:
https://github.com/Dani3lSun/docker-db-apex-dev/issues/4

**Comment by PhilippSalvisberg** [comment]
Thank you @Dani3lSun for letting me know. Very interesting. 

However, there has to be at least one additional option to enable su on Oracle Linux 7.3 since the official [12.1 image](https://store.docker.com/images/oracle-database-enterprise-edition) - which is running on OL 7.3 as well - has the su capability without configuring [Runtime privilege and Linux capabilities](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities). Here's the recommended run command (I've used it with 3g instead of 8g to save memory on my MacBook).

```
docker run -d --env-file ./db_env.dat -p 1527:1521 -p 5507:5500 -it --name dockerDB --shm-size="8g" store/oracle/database-enterprise:12.1.0.2
``` 

I let you know when I find out what makes su possible in non-privileged mode.
